name: Upload artifacts
# https://github.com/google-github-actions/auth#authenticating-to-container-registry-and-artifact-registry

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Upload artifacts to an Artifact Registry.
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure Workload Identity Federation via a credentials file.
      - name: Authenticate to gcp
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credential_file: true
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      # Install gcloud, 'setup-gcloud' automatically picks up authentication from 'auth'.
      - name: Set up Cloug SDK.
        uses: google-github-actions/setup-gcloud@v0

      # Now you can run gcloud commands authenticated as the impersonated service account
      - id: configure-docker
        name: Configure gcloud for docker.
        run: |
          gcloud --quiet --project="${{ secrets.GCP_PROJECT_ID }}" auth configure-docker asia.gcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.GITHUB_ACTION_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
